### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

In [1]:
import numpy as np  # import numpy library

In [2]:
np.__version__

'2.0.2'

In [3]:
A=np.array([[5, 10, 15, 20],
              [25, 30, 35, 40],
              [45, 50, 55, 60],
              [65, 70, 75, 80]])
print(A)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]


EXPLANATION: I made a NumPy array A with my numbers like this: [[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60], [65, 70, 75, 80]].

In [4]:
print(A.shape)

(4, 4)


EXPLANATION: I used A.shape to see that it has 4 rows and 4 columns.

In [5]:
print(A.max())

80


EXPLANATION: Then I used A.max() to find the biggest number, which is 80.

In [6]:
print(np.max(A))

80


EXPLANATION: I also used np.max(A) to do the same thing using a NumPy function.

B. Create a 5x5 integer-array filled with ones.

In [7]:
B = np.ones((5,5), dtype=int)

EXPLANATION: created a 5x5 NumPy array B filled with ones using np.ones((5,5), dtype=int).

In [8]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


EXPLANATION: Then I printed B to see all the elements, and it shows a 5x5 grid where every number is 1.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [9]:
C = np.arange(-5, 6)

In [10]:
C = C*2

In [11]:
print(C)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]
